### ISSUE TITLE
streams2

### ISSUE THREAD

**Issue by indexzero** [nodejitsu/godot#15]
We are going to need to do a non-trivial refactor for `streams2` when it's ready, but we should not wait for `node@0.10.x`

**Comment by mmalecki** [comment]
Assigning this to myself, I hate `streams2` enough to do the refactor.

**Comment by jcrugzz** [comment]
@mmalecki Let me know when you start this and I'll help you out.

**Comment by indexzero** [comment]
`streams2` is important when _your reader is faster than your writer_, but because reactors in godot are designed to reduce the number of events read through filtering, mutating and otherwise fuxing with _this scenario is unlikely to ever happen._
