### ISSUE TITLE
Error on godot createServer?

### ISSUE THREAD

**Issue by siygle** [nodejitsu/godot#19]
Just want to try a little bit on godot and follow readme guideline, but it will always throw error during createServer?

> /home/ferrari/Programming/nodejs/nodejs-experiment/node_modules/godot/lib/godot/net/server.js:148
>       throw err;
>             ^
> undefined

https://github.com/nodejitsu/godot/blob/master/lib/godot/net/server.js#L134-L150
When it create server and listen, will go into this function, but responded is false and it will always throw error in the end, is this correct? Or just I use the wrong way to create godot server? thanks

**Comment by indexzero** [comment]
Can you gist the code you're using? There may be an error in the example.

**Comment by mmalecki** [comment]
b42ddbf should fix it.
