### ISSUE TITLE
Add configuration for emitter.setMaxListeners

### ISSUE THREAD

**Issue by jcrugzz** [nodejitsu/godot#48]
Ran into this with the `by` reactor. It sends the warning when it is piping to new reactor streams as that adds a data listener for each `pipe` that is called.

**Comment by mmalecki** [comment]
It shouldn't be a configuration, I think we should just disable the check (`emitter.setMaxListeners(0)`) wherever it's sane to do it (e.g. reactors).

**Comment by jcrugzz** [comment]
meant `configurable` but yea it shouldn't be an issue so I'll just do that.

**Comment by jcrugzz** [comment]
fixed in 2e204372bb4e332c8e1037297f4be49104135350
